<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>EJLive.Monitoring</AssemblyName>
    <RootNamespace>EJLive.Monitoring</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EJLive.Core\EJLive.Core.csproj" />
    <ProjectReference Include="..\EJLive.Shared\EJLive.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
  </ItemGroup>
</Project>
