<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>EJLive.Tests</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.0.2" />
    <PackageReference Include="MSTest.TestFramework" Version="3.0.2" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Samples\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EJLive.Application\EJLive.Application.csproj" />
    <ProjectReference Include="..\EJLive.Business\EJLive.Business.csproj" />
    <ProjectReference Include="..\EJLive.Client.Service\EJLive.Client.Service.csproj" />
    <ProjectReference Include="..\EJLive.Client.WinForms\EJLive.Client.WinForms.csproj" />
    <ProjectReference Include="..\EJLive.Server\EJLive.Server.csproj" />
    <ProjectReference Include="..\EJLive.Server.WinForms\EJLive.Server.WinForms.csproj" />
    <ProjectReference Include="..\EJLive.Core\EJLive.Core.csproj" />
    <ProjectReference Include="..\EJLive.Shared\EJLive.Shared.csproj" />
  </ItemGroup>
</Project>
