#!/usr/bin/env python3
"""Service activation ledger.

Every `*Service` / `*Manager` / `*Engine` / `*Store` type in the compiled set is
classified by how (and whether) it reaches a running process:

  host        constructed by an entry point (Program.cs / MainForm / Worker)
  registry    constructed through the service registry / gateway activation batch
  orphan      declared and compiled, never constructed  -> dead surface
  reference   constructed only from demoted/archive code  -> shadow surface

`orphan` and `reference` rows are the Wave-1 work list; the count is quoted in
docs/EJLIVE-ENGINEERING-PROMPT.md SS17 and must shrink, never grow.

    python3 tools/inventory/service_activation.py            # rewrite the csv
    python3 tools/inventory/service_activation.py --check     # CI drift check
"""
from __future__ import annotations

import csv
import importlib
import io
import os
import re
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "tools", "inventory"))
inv = importlib.import_module("ejlive_inventory")

OUT = "docs/12-service-activation-status.csv"
SUFFIX = ("Service", "Manager", "Engine", "Store", "Gateway", "Registry", "Orchestrator", "Runner", "Supervisor")
ENTRY_HINT = re.compile(r"(Program|MainForm|DashboardForm|Worker|Bootstrap|Startup|Console)")


def main() -> int:
    projects = inv.load_projects()
    active = sorted({f for p in projects.values() for f in p.compiled})
    ref_root = os.path.join(ROOT, "src", "_reference")
    ref_files = [os.path.relpath(os.path.join(dp, f), ROOT).replace(os.sep, "/")
                 for dp, _, fn in os.walk(ref_root) for f in fn if f.endswith(".cs")] if os.path.isdir(ref_root) else []
    text = {f: inv.read(f) for f in active}
    rtext = {f: inv.read(f) for f in ref_files}
    proj_of = {f: n for n, p in projects.items() for f in p.compiled}

    decl: dict[str, tuple[str, str]] = {}
    for f in active:
        for ns, ty, ln, partial in inv.declarations(f):
            simple = ty.split(".")[-1]
            if simple.endswith(SUFFIX):
                decl.setdefault(simple, (f, ns))

    rows = []
    for name, (f, ns) in sorted(decl.items()):
        ctor = re.compile(r"new\s+" + re.escape(name) + r"\s*[<(]")
        host = [g for g, t in text.items() if ctor.search(t) and ENTRY_HINT.search(os.path.basename(g))]
        reg = [g for g, t in text.items() if ctor.search(t) and g not in host]
        consumers = [g for g, t in text.items() if re.search(r"\b" + re.escape(name) + r"\b", t) and g != f]
        shadow = [g for g, t in rtext.items() if ctor.search(t)]
        if host:
            status, via = "host", os.path.basename(host[0])
        elif reg:
            status, via = "registry", os.path.basename(reg[0])
        elif shadow:
            status, via = "reference-only", os.path.basename(shadow[0])
        else:
            status, via = "orphan", ""
        rows.append([name, ns or "-", proj_of.get(f, "-"), os.path.relpath(os.path.join(ROOT, f), ROOT).replace(os.sep, "/"),
                     len(consumers), len(host) + len(reg), status, via])
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(["type", "namespace", "project", "file", "consumers", "construction_sites", "activation", "activated_from"])
    w.writerows(rows)
    content = ("# service activation status -- generated by tools/inventory/service_activation.py\n"
               "# orphans and reference-only rows are the Wave-1 promotion backlog (docs/EJLIVE-ENGINEERING-PROMPT.md SS17)\n"
               + buf.getvalue())
    if "--check" in sys.argv:
        cur = open(os.path.join(ROOT, OUT), encoding="utf-8").read() if os.path.isfile(os.path.join(ROOT, OUT)) else None
        if cur == content:
            print(f"activation ledger fresh ({len(rows)} rows)")
            return 0
        print("activation ledger drift -- regenerate: python3 tools/inventory/service_activation.py")
        return 1
    with open(os.path.join(ROOT, OUT), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    tally = defaultdict(int)
    for r in rows:
        tally[r[6]] += 1
    print(f"{len(rows)} service types: " + ", ".join(f"{k}={v}" for k, v in sorted(tally.items())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
