// One declaration per enum, carrying the union of the members its merged variants declared.
// Regenerated by `python3 tools/gates/check_merge_dumps.py --repair-enum-file <path>`; the
// values are those the variants agreed on, so no call site loses or renumbers a member.
namespace EJLive.Core.Enums
{

    public enum AlertSeverity
    {
        Info = 0,
        Warning = 1,
        Critical = 2,
        Emergency = 3
    }

    public enum ATMStatus
    {
        Online = 1,
        Offline = 2,
        InService = 3,
        Supervisor = 4,
        Fault = 5,
        Maintenance = 6,
        Unknown = 7
    }

    public enum ATMType
    {
        NCR = 1,
        GRG = 2,
        WN = 3,
        Diebold = 4,
        Hyosung = 5
    }

    public enum CommandType
    {
        Heartbeat = 0,
        CMD_RESTART = 1,
        CMD_SCREENSHOT = 2,
        CMD_TIMESYNC = 3,
        CMD_CHGPWD = 4,
        CMD_SENDIMG = 5,
        CMD_GHOSTREMOTE = 6,
        CMD_GETLOG = 7,
        CMD_UPDATECONFIG = 8,
        CMD_PING = 9,
        ACK = 99,
        NAK = 98,
        FileChunk = 100,
        FileStart = 101,
        FileEnd = 102
    }

    public enum ConnectionType
    {
        LAN = 1,
        ADSL = 2,
        CDMA = 3,
        GSM = 4,
        VPN = 5
    }

    public enum DeviceComponent
    {
        Printer = 1,
        CardReader = 2,
        CashDispenser = 3,
        ReceiptPrinter = 4,
        PINPad = 5,
        Camera = 6,
        NetworkModule = 7,
        UPS = 8
    }

    public enum JournalFileType
    {
        EJDATA_LOG = 1,
        EJRCPY_LOG = 2,
        EJDATA_LOB = 3,
        TRACE = 4,
        EJ = 5
    }

    public enum LogLevel
    {
        Debug = 0,
        Info = 1,
        Warning = 2,
        Error = 3,
        Fatal = 4
    }

    public enum SyncStatus
    {
        Idle = 0,
        Storing = 1,
        Syncing = 2,
        InProgress = 3,
        Resyncing = 4,
        Completed = 5,
        Failed = 6,
        Paused = 7,
        Archived = 8
    }

    public enum TransactionType
    {
        CashWithdrawal = 1,
        BalanceInquiry = 2,
        Transfer = 3,
        Deposit = 4,
        PinChange = 5,
        MiniStatement = 6,
        BillPayment = 7,
        TopUp = 8,
        Unknown = 99
    }
}
