<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\EJLive.Core\EJLive.Core.csproj" />
    <ProjectReference Include="..\EJLive.Server\EJLive.Server.csproj" />
    <ProjectReference Include="..\EJLive.Shared\EJLive.Shared.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultItems>false</EnableDefaultItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>EJLive.Server.WinForms</AssemblyName>
    <RootNamespace>EJLive.Server.WinForms</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="ServerMainForm.cs" />
    <Compile Include="PromptTextDialog.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
</Project>
