<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>EJLive.Backup</AssemblyName>
    <RootNamespace>EJLive.Backup</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EJLive.Core\EJLive.Core.csproj" />
    <ProjectReference Include="..\EJLive.Shared\EJLive.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
  </ItemGroup>
</Project>
